services:
  - type: web
    name: ecoco-complaint-analyzer
    env: python
    repo: https://github.com/fen-ecoco/fen-ecoco-complaint_webapp2
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run complaint_webapp.py --server.port $PORT --server.address 0.0.0.0"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
